#!/usr/bin/env bash


setup_nix() {
    packages="zsh vim"
    sudo apt update -y
    sudo apt upgrade -y
    sudo apt install -y $packages

    if [ ! "$SHELL" -ef "$(which zsh)" ]; then
        echo "Change SHELL to $(which zsh)..."
        chsh -s $(which zsh)
    fi
}

setup_osx() {
    packages="zsh"
    brew update
    brew install $packages
}

case "$(uname -a)" in
    *Ubuntu*)
        setup_nix
        ;;
    Darwin*)
        setup_osx
        ;;
    *)
        echo "unknown os";
        exit 1
        ;;
esac
