#!/usr/bin/env bash

setup_cmn()
{
    if [ ! -e ~/.emacs.d ]; then
        git clone git@github.com:syl20bnr/spacemacs.git ~/.emacs.d -b develop
    fi
}

setup_nix()
{
    echo "=> Install apt packages"
    editors="emacs neovim python3-neovim vim"
    windowmanagers="sway sway-backgrounds swaybg swayidle swaylock"
    devutils="cargo cmake build-essential tig"
    miscutils="curl dex fasd fzf htop mpv multitail ncdu ripgrep rofi tldr tmux tmux-themepack-jimeh zsh"
    packages="$editors $windowmanagers $devutils $miscutils"
    sudo apt-get update -qq -y
    sudo apt-get upgrade -qq -y
    sudo apt-get install -qq -y $packages

    if [ ! "$SHELL" -ef "$(which zsh)" ]; then
        echo "=> Change SHELL to $(which zsh)"
        chsh -s $(which zsh)
    fi
}

setup_osx()
{
    if ! which brew 2>&1 > /dev/null; then
        echo "=> Install homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    echo "=> Install homebrew packages"
    packages="fasd fzf mpv ripgrep tmux zsh"
    brew update
    brew install $packages
}

case "$(uname -a)" in
    *Ubuntu*)
        setup_cmn
        setup_nix
        ;;
    Darwin*)
        setup_cmn
        setup_osx
        ;;
    *)
        echo "unknown os";
        exit 1
        ;;
esac
