#!/usr/bin/env bash

setup_cmn() {
    echo "=> Clone tmux-themepack"
    if [ ! -e ~/.tmux-themepack ]; then
        git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
    fi
}

setup_nix() {
    echo "=> Install apt packages"
    packages="arandr cargo ncdu htop build-essential cmake tig silversearcher-ag multitail zsh vim tmux mpv"
    sudo apt update -y
    sudo apt upgrade -y
    sudo apt install -y $packages

    if [ ! "$SHELL" -ef "$(which zsh)" ]; then
        echo "=> Change SHELL to $(which zsh)"
        chsh -s $(which zsh)
    fi

    if ! which rg 2>&1 > /dev/null; then
        echo "=> Installing ripgrep"
        curl -ssf https://static.rust-lang.org/rustup.sh | sh
        cargo install ripgrep
    fi

}

setup_osx() {
    if ! which brew 2>&1 > /dev/null; then
        echo "=> Install homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    echo "=> Install homebrew packages"
    packages="zsh tmux mpv ripgrep nodejs"
    brew update
    brew install $packages
}

case "$(uname -a)" in
    *Ubuntu*)
        setup_cmn
        setup_nix
        ;;
    Darwin*)
        setup_cmn
        setup_osx
        ;;
    *)
        echo "unknown os";
        exit 1
        ;;
esac
